apiVersion: v1
kind: Service
metadata:
  name: clickhouse-exporter
  namespace: default
  labels:
    app: clickhouse-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9116
      targetPort: 9116
  selector:
    app: clickhouse-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-exporter
  namespace: default
  labels:
    app: clickhouse-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-exporter
  template:
    metadata:
      labels:
        app: clickhouse-exporter
    spec:
      containers:
        - name: clickhouse-exporter
          image: f1yegor/clickhouse-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9116
              name: metrics
          env:
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-auth
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-auth
                  key: CLICKHOUSE_PASSWORD
          args:
            - "-scrape_uri=http://clickhouse:8123/"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"