apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: milvus
spec:
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
    - name: http
      port: 9091
      targetPort: 9091
  type: ClusterIP
  selector:
    app: milvus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-standalone
  namespace: milvus
spec:
  serviceName: milvus-standalone
  replicas: 1
  selector: 
    matchLabels: 
      app: milvus
  template:
    metadata: 
      labels: 
        app: milvus
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.6.3
          command: ["milvus", "run", "standalone"]
          env:
            - name: ETCD_ENDPOINTS
              value: "milvus-etcd:2379"
            - name: MINIO_ADDRESS
              value: "milvus-minio:9000"
          ports:
            - containerPort: 19530
              name: grpc
            - containerPort: 9091
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 32Gi
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
      volumes:
        - name: milvus-data
          persistentVolumeClaim:
            claimName: milvus-data
  volumeClaimTemplates:
    - metadata:
        name: milvus-data
      spec:
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 10Gi
        storageClassName: default