apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
  namespace: milvus
spec:
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  clusterIP: None
  selector:
    app: milvus-minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-minio
  namespace: milvus
spec:
  serviceName: milvus-minio
  replicas: 1
  selector: 
    matchLabels: 
      app: milvus-minio
  template:
    metadata: 
      labels: 
        app: milvus-minio 
    spec:
      containers:
        - name: milvus-minio
          image: minio/minio:RELEASE.2024-12-18T13-15-44Z
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 4Gi
          args:
            - server
            - /minio_data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: milvus-minio-data
              mountPath: /minio_data
      volumes:
        - name: milvus-minio-data
          persistentVolumeClaim:
            claimName: milvus-minio-data
  volumeClaimTemplates:
    - metadata:
        name: milvus-minio-data
      spec:
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 100Gi
        storageClassName: default