apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: monitor-dashbord
  labels:
    app: alertmanager-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-server
  template:
    metadata:
      labels:
        app: alertmanager-server
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.28.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager/

      volumes:
        - name: alertmanager-config-volume
          configMap:
            defaultMode: 420
            name: alertmanager-server-conf
