apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-deployment
  namespace: monitor-dashbord
  labels:
    app: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter
          ports:
            - containerPort: 9115
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: blackbox-config-volume
              mountPath: /etc/blackbox_exporter/

      volumes:
        - name: blackbox-config-volume
          configMap:
            defaultMode: 420
            name: blackbox-server-conf

  volumeClaimTemplates:
    - metadata:
        name: blackbox-config-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
        storageClassName: default
        volumeMode: Filesystem

