apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitor-dashbord
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 300M
            limits:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana/

      volumes:
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: grafana-storage-pvc