apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./cluster-role.yaml
- ./cluster-role-binding.yaml
- ./kube-state-metrics-service-account.yaml
- ./kube-state-metrics-deployment.yaml
- ./alertmanager-config-map.yaml
- ./alertmanager-deployment.yaml
- ./prometheus-config-map.yaml
- ./prometheus-deployment.yaml

