apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitor-dashbord
  labels:
    app: prometheus-service
spec:
  type: LoadBalancer
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-server

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitor-dashbord
  labels:
    app: alertmanager-service
spec:
  type: LoadBalancer
  ports:
    - name: alertmanager
      port: 9093
      targetPort: 9093
  selector:
    app: alertmanager-server

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitor-dashbord
  labels:
    app: grafana-service
spec:
  type: LoadBalancer
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    app: grafana-server
