apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 27017
      name: server
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default
spec:
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: mongodb
          imagePullPolicy: IfNotPresent
          image: mongo:8.0.15
          ports:
            - containerPort: 27017
              name: server
          volumeMounts:
            - name: mongodb-storage-volume
              mountPath: /data/db
      volumes:
        - name: mongodb-storage-volume
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: default
        volumeMode: Filesystem
  selector:
    matchLabels:
      app: mongodb