apiVersion: v1
kind: Service
metadata:
  name: frpc-internal
  namespace: default
  labels:
    app: frpc-internal
    project: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  type: LoadBalancer
  selector:
    app: frpc
  ports:
    - port: 7400
      name: web-server
      targetPort: 7400
