apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: default
  labels:
    app: kafka-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  selector:
    app: kafka-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: default
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9308
              name: metrics
          args:
            - "--kafka.server=kafka:9092"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"