apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: default
  labels:
    app: kafka-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: default
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: ghcr.io/kafbat/kafka-ui:07c4351
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LOGGING_LEVEL_ROOT
              value: info
            - name: LOGGING_LEVEL_COM_PROVECTUS
              value: info
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:9092
            - name: KAFKA_CLUSTERS_0_METRICS_PORT
              value: "9997"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"