###使用自建数据库；使用Ingress发布配置后台###
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: server
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
spec:
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: redis
          imagePullPolicy: IfNotPresent
          image: redis:8.2.2
          ports:
            - containerPort: 6379
              name: server
          resources:
            limits:
              cpu: 2
              memory: 32Gi
          args: 
            - /usr/local/etc/redis/conf/redis.conf
          volumeMounts:
            - name: redis-config-volume
              mountPath: /usr/local/etc/redis/conf
            - name: redis-storage-volume
              mountPath: /data
      volumes:
        - name: redis-config-volume
          configMap:
            defaultMode: 420
            name: redis-server-conf
        - name: redis-storage-volume
  volumeClaimTemplates:
    - metadata:
        name: redis-storage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: default
        volumeMode: Filesystem
  selector:
    matchLabels:
      app: redis